plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - .idea
  - node_modules
  - Gemfile.lock
  - Gemfile
  - package.json
  - package-lock.json
  - CNAME
  - gulpfile.js
  - _config.dev.yml

#Others
markdown: kramdown
port: 4002

markdown_ext: markdown,md,liquid
future: true

# Setup
title: Alla Romasheva
summary: UX/UI designer
logo: /dist/favicon/android-icon-192x192.png
url: https://romasheva.com
baseurl: ''
email: alla@romasheva.com
analytics: UA-37629144-3
sharethis: property=5bbb3b137283210011cb6359&product=inline-share-buttons

social:
  name: Alla Romasheva (Алла Ромашева)

profiles:
  facebook: https://www.facebook.com/romasheva.design/
  twitter: https://twitter.com/AllaRomasheva
  instagram: https://www.instagram.com/romasheva.design/
  linkedin: https://www.linkedin.com/in/romasheva/
  behance: https://www.behance.net/romasheva
  pinterest: https://www.pinterest.com/romasevaalla38/
  dribbble: https://dribbble.com/romasheva
  github: https://github.com/allaromasheva
  pexels: https://www.pexels.com/@alla-romasheva-3820560/

contacts:
  telegram: https://t.me/romasheva
  skype: skype:live:37e58384221057fa?chat
  messenger: https://m.me/romasheva.design

twitter:
  username: allaromasheva

facebook:
  publisher: 100024493295482
  chat: 100930458520274

author:
  name: Alla Romasheva
  url: https://romasheva.design/
  twitter: allaromasheva
  image:
    path: /dist/images/cover.jpg
    height: 512
    width: 512

defaults:

  - scope:
      path: ''
    values:
      lang: 'en'
      layout: 'default'
      image:
        path: '/dist/images/cover.jpg'
        width: '1000'
        height: '600'

  - scope:
      path: '_posts/uk'
    values:
      layout: 'post'
      lang: uk
      permalink: '/uk/:year/:title.html'


  - scope:
      path: '_posts/en'
    values:
      layout: 'post'
      lang: en
      permalink: '/en/:year/:title.html'

  - scope:
      path: 'page/uk'
    values:
      lang: 'uk'
      seo:
        links:
          - https://romasheva.design/uk/
          - https://romasheva.cv/uk/

  - scope:
      path: 'page/en'
    values:
      lang: 'en'
      seo:
        links:
          - https://romasheva.design/en/
          - https://romasheva.cv/en/
