plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - .idea
  - node_modules

#Others
markdown: kramdown
port: 4002

markdown_ext: markdown,md,liquid

# Setup
title: Alla Romasheva
summary: UX/UI designer
logo: /assets/favicon/android-icon-192x192.png
url:  https://romasheva.com
baseurl: ''
email: alla@romasheva.com
analytics: UA-37629144-3
sharethis: property=5bbb3b137283210011cb6359&product=inline-share-buttons

social:
  name: Alla Romasheva (Алла Ромашева)
  links:
    - https://romasheva.cv/
    - https://romasheva.design/
    - https://www.facebook.com/romasheva.design/
    - https://www.instagram.com/romasheva.design/
    - https://twitter.com/AllaRomasheva
    - https://linkedin.com/in/romasheva/
    - https://www.behance.net/romasheva
    - https://dribbble.com/romasheva
    - https://ua.linkedin.com/in/romasheva
    - https://github.com/allaromasheva
  profiles:
    facebook: https://www.facebook.com/romasheva.design/
    instagram: https://www.instagram.com/romasheva.design/
    twitter: https://twitter.com/allaromasheva
    linkedin: https://linkedin.com/in/romasheva/
    behance: https://www.behance.net/romasheva
    pinterest: https://www.pinterest.com/romasevaalla38/
    dribbble: https://dribbble.com/romasheva
    github: https://github.com/allaromasheva
    pexels: https://www.pexels.com/@alla-romasheva-3820560/

twitter:
  username: allaromasheva

facebook:
  publisher: 100024493295482
  chat: 100930458520274

author:
  name: Alla Romasheva
  url: https://romasheva.com/
  twitter: allaromasheva
  image:
    path:  /assets/images/alla.romasheva.jpeg
    height: 512
    width: 512

defaults:

  - scope:
      path: ''
    values:
      lang: 'en'
      layout: 'default'
      alternate:
        en: '/en/'
        ru: '/ru/'
        uk: '/uk/'
      image:
        path: '/assets/images/cover.jpg'
        width: '1000'
        height: '600'
      seo:
        links:
          - https://romasheva.design/
          - https://romasheva.cv/
          - https://www.facebook.com/romasheva.design/
          - https://www.instagram.com/romasheva.design/
          - https://twitter.com/allaromasheva
          - https://www.linkedin.com/in/romasheva/
          - https://www.behance.net/romasheva
          - https://dribbble.com/romasheva
          - https://ua.linkedin.com/in/romasheva/
          - https://github.com/allaromasheva
          - https://www.pexels.com/@alla-romasheva-3820560/

  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:categories/:title.html'

  - scope:
      path: 'page/uk'
    values:
      lang: 'uk'
  - scope:
      path: 'page/en'
    values:
      lang: 'en'
  - scope:
      path: 'page/ru'
    values:
      lang: 'ru'

